### ISSUE TITLE
Extra paste when ctrl-v 2x quickly (total of 3 pastes, when I only pasted twice)

### ISSUE THREAD

**Issue by dougcassidy** [ffMathy/Shapeshifter#1]
I often get an extra paste, when I am using regular Copy&Paste (with Shapeshifter on). Often, I will select a line of code (any app) and quickly copy, then paste twice: one is just to paste down what is already there and then once more to duplicate the line. So, I go: select, copy, paste, paste. That should just duplicate the line (and does, normally). What happens is I wind up with *3* of the selected lines. This does *not* happen if I hit copy,paste,paste slowly. Only if I hit ctrl-v, ctrl-v quickly.

**Comment by ffMathy** [comment]
Hi - sorry for the late reply. Thanks for the report! We'll get this fixed in Shapeshifter 5. Shapeshifter 5 is a complete rewrite, which will have a new core that is very compact and stable. Shapeshifter 4 (that you are currently using) is quite unstable.

I will let you know in this thread when Shapeshifter 5 is out.

**Comment by ffMathy** [comment]
Do you release CTRL between the two quick pastes, or do you keep holding it down?

**Comment by dougcassidy** [comment]
No i keep it held down.  select, ctrl->c->v->v  I keep ctrl held for the whole sequence.

**Comment by ffMathy** [comment]
This has now been resolved. Thanks for your feedback, and keep it up!
