### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#122]
Right now, the latest release of Shapeshifter crashes (`shapeshifter-v6.0.0.1789`) silently. We should improve the global error handler so that it at least displays errors like these as well, in a `MessageBox`. Furthermore, the error handler should log the exception to the `Logger`.

**Comment by ffMathy** [comment]
@dvitonis or @KoalaBear84, do you have any idea of what could be causing this crash silently? It doesn't crash when debugging in Visual Studio, so I think it has something to do with the `InstallArgumentProcessor` when it tries to install itself.

But still, the global error handler should have kicked in.

**Comment by KoalaBear84** [comment]
Had no time during the day. Will try to check this evening.

**Comment by ffMathy** [comment]
That would be awesome, thanks.

**Comment by KoalaBear84** [comment]
ShapeShifter works outside of Visual Studio, but only when I start it from the builded path. (With the PDB's etc. in the same folder, see next). I can reproduce the issue if I copy the ShapeShifter.exe to another folder.

I see that ShapeShifter.exe is stopped almost immediately. In the event log I saw the following:
    Problem signature:
    P1: Shapeshifter.exe
    P2: 6.0.0.1789
    P3: 56989da1
    P4: PresentationFramework
    P5: 4.6.1063.1
    P6: 56536f0d
    P7: 2f3
    P8: f
    P9: System.IO.FileNotFoundException
    P10: 

In SysInternals - Process Monitor I saw this:
    C:\Windows\Microsoft.NET\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.pdb
    C:\Windows\symbols\dll\WindowsBase.pdb
    C:\WINDOWS\dll\WindowsBase.pdb
    C:\Windows\WindowsBase.pdb

So it looks like it tries to search for the PDB now, which you mentioned to include in the executable. And maybe because ShapeShifter is already in a bad state (reason probably unknown) the dynamically loading of DLLs (and maybe PDB's too) does not work anymore.

If you also include PDB in executable, you might also want / need to load them (second parameter of Assembly.Load):
http://stackoverflow.com/questions/7836737/debug-dynamically-loaded-assembly

Also I see the icon is not in the repository, and I get the windows default icon because of this.

I hope you have some more insight about what happens, enough to solve what become broken since the last (good!) changes. :)

**Comment by ffMathy** [comment]
Aaaaaah! That explains it. I screwed up recently. I fixed it now.

**Comment by ffMathy** [comment]
Thanks a lot for your hard work!

**Comment by ffMathy** [comment]
The issue is solved in #123. It's because I recently switched to a nice build process that takes all dependent `.dll` files and embeds them in `Shapeshifter.exe` so that they don't need to be referenced. It even supports embedding the `.pdb` files with it too, for full debugging.

However, there was one thing I was missing. When compiling `Shapeshifter.exe`, I couldn't include `Shapeshifter.pdb` as an embedded resource because it was not yet generated at that phase (it would require a double-compilation). So now, Shapeshifter properly double-compiles.

After the first compilation, it embeds the `Shapeshifter.pdb` file into the second compilation. This allows the `.pdb` file to be included in the `Program Files` installation, and hence have full line numbers and debugging information, but only as a single executable.

**Comment by ffMathy** [comment]
Nevermind, it actually still doesn't work when removing the `.dll` files locally. Sorry. I'll try better.

**Comment by ffMathy** [comment]
Alright, it should be good now. Instead of attempting to bundle DLLs into the executable myself, I have now used `Costura.Fody` for that instead. It seems to be more reliable and stable.

Current builds of Shapeshifter will be entirely broken and will need to be redownloaded.

I will test it myself in a few minutes when the build finishes.

**Comment by ffMathy** [comment]
Close, but no cigar. I'll try disabling the recent weaver I added, since it is running locally (even outside Visual Studio) without issues now.

**Comment by ffMathy** [comment]
IT'S ALIVE!!!

**Comment by KoalaBear84** [comment]
Good!

At work we use https://visualstudiogallery.msdn.microsoft.com/a7196a81-67fc-4a26-a88a-b68ef31c2266 for this, but that is an extension for Visual Studio, which is absolutely not an option for GitHub. And myself I always use the same code you previously had without any issues. Assembly.Load code. The only thing you always need to ignore is "*.resources" assemblyName's.

But if this is now working, it's great. And looks more solid.
