### ISSUE TITLE
Shapeshifter should start with Windows as default

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#139]

**Comment by KoalaBear84** [comment]
Here are some nice code examples, the seperate class example would be nice. The only problem could be that ShapeShifter is not running with Administrator rights? Is that correct, because we now go around the requirement of Administrator rights with the signing. And I guess you cannot register the application as startup without Admin rights.

http://stackoverflow.com/questions/5089601/run-the-application-at-windows-startup

**Comment by ffMathy** [comment]
We already do it in the settings window. It's no problem. It just needs to be default :D

**Comment by ffMathy** [comment]
And no, it doesn't require administrative privileges. `HKEY_LOCAL_MACHINE` is UAC protected, but `HKEY_CURRENT_USER` is not. We just put it in the `HKEY_CURRENT_USER\Microsoft\Windows\CurrentVersion\Run` key currently, and it works fine.

**Comment by KoalaBear84** [comment]
Indeed. :)
