### ISSUE TITLE
All text is pasted as plain text

### ISSUE THREAD

**Issue by msuguy71** [ffMathy/Shapeshifter#168]
Since releasing version 6.1.1919, it seems as all text is pasted as plain text, even when selecting paste as is from the UI.  Went to copy and paste an APA reference and it pasted into Word 2013 without the italics for the journal name.  I then tried copying bolded text in Word and it pasted as plain text.

**Comment by ffMathy** [comment]
Did this work before? I am curious because I don't think we have changed anything in that sense.

**Comment by msuguy71** [comment]
Yep.  it was working in the previous release

**Comment by ffMathy** [comment]
Note to self: Is this unit testable? If so, make a test for it.

**Comment by msuguy71** [comment]
This also happens in MS Office 2016 for me.

**Comment by thegabriestein** [comment]
Assuming this is a currently occurring bug? Definitely feeling it in a number of use cases. Was just trying to copy some formatted text where keeping the specific formatting (bold, color, and hyperlink) would be a benefit of Shapeshifter. And it was stripping the formatting. 

Definitely better to have plain text no formatting, than for it to be applying a random format to everything. But the ability to retain formatting is part of the goal to "efficiently manage information".

Also, is it planned functionality to have Control + V = paste, but Control + Shift + V = clean paste? I definitely appreciated this in v5 and used it very frequently (despite some lag waiting for the UI to trigger so it would clean the formatting). I'll make an issue for this if it's not already planned since it's super helpful.

**Comment by ffMathy** [comment]
Good idea!

**Comment by thegabriestein** [comment]
Cool, made an issue for it in #279! It is a really valuable keybind in many many cases, I'm feeling it not having it.

**Comment by ffMathy** [comment]
I need detailed steps to reproduce.

Can you guys provide some in list-form?

**Comment by ffMathy** [comment]
This has now been fixed and will ship with the next release.
