### ISSUE TITLE
Is it possible to avoid exe/dll files in sourcode?

### ISSUE THREAD

**Issue by urza** [ffMathy/Shapeshifter#193]
Hi,
by briefly examining the source code of Shapeshifter, I noticed there are some .exe and .dll files linked. Which means I cannot examine the full source code and trust the application. In the exe/dll files can be easily hidden malicious code.

It is a break dealer for me, as I cant trust this application.

Can the application be built from source code only, without these added exe/dll files?
If not, can you document what these are, and where to get them from trusted source?

Thank you very much

**Comment by ffMathy** [comment]
No, it is not possible to avoid that. The exe files comes from installing the NuGet package EasyHook. Adding the source codes is not a good idea, since these exe files are written in C++, and I fear it will reduce the chance of people contributing to Shapeshifter.

EasyHook is a library which allows Shapeshifter to inject DLLs into other processes. It is currently an experimental feature that injects the interceptor project into the process of things like Remote Desktop, allowing Shapeshifter to overrule the CTRL+V combination which remote desktop processes normally override.

What you can do is check out the source codes or binaries of EasyHook (https://easyhook.github.io/), run an MD5 hash of the executable there, and compare it with the MD5 hash of the executables in Shapeshifter. Then you will see that they are identical and unmodified.

This is generally a good point, so I will add a section about it in the documentation in the weekend.

**Comment by ffMathy** [comment]
This has been added to the documentation in #194.

**Comment by urza** [comment]
Thanks for your clarification.

If Easyhook is obtainable from NuGet, then you shouldnt need to attach the exe and dlls into this repository. Rather just keep them on your developer machine and only submit the nuget packages in packages.config file and Visual Studio will take care of it. Or am I missing something?

Anyway, I am a little bit worried using program which can inject into other processes. Maybe it is just me being paranoid in general. I dont mean it in sense that ShapeShifter itself needs to be malicious, but it increases the attack area and in general increses risk of some malicious attacker to succeed. Maybe it would be good to offer build without this functionality that would not need EasyHook at all?

**Comment by ffMathy** [comment]
You are missing something in regards to the NuGet. Some packages actually install executables or content files into your project. The reason EasyHook does this, is because the executables are compiled in C++ (they can't be added as references). And the reason they are written in C++ is because C# doesn't have APIs to do DLL injection at all in the first place, or support for so-called "low level hooks".

I'm sorry, but how does DLL injection increase the "attack area"? There is nothing about DLL injection that is dangerous. In fact, many applications including TeamViewer do it all the time. It just happens to be used by viruses as well, but for very different reasons. Kind of like both TeamViewer and a virus needs access to the memory, or the disk.

Everything you need to know is here: https://github.com/ffMathy/Shapeshifter/blob/d067192e192b7e79bbcf23e9f6deb8817f59a60f/src/Shapeshifter.WindowsDesktop/Services/Keyboard/KeyboardDominanceWatcher.cs

Notice the `SuspiciousProcesses` string array. It contains the list of processes that Shapeshifter will inject its module into. The module that is injected is the `Shapeshifter.WindowsDesktop.KeyboardHookInterception` class library, which you can [find here](https://github.com/ffMathy/Shapeshifter/tree/d067192e192b7e79bbcf23e9f6deb8817f59a60f/src/Shapeshifter.WindowsDesktop.KeyboardHookInterception).

**Comment by urza** [comment]
Ok, that is good enough for me. Thanks for explanation.

**Comment by ffMathy** [comment]
However, I must mention that the worst-case scenario is indeed that if the Shapeshifter module crashes, the host process (remote desktop) etc might terminate as well. But that's really the worst-case, and you can just start it up again.
