### ISSUE TITLE
Snipping Tool Incompatibility

### ISSUE THREAD

**Issue by bradgarner** [ffMathy/Shapeshifter#200]
Hello, I am new to Shapeshifter and I would like to say that this is a pretty neat app and it is helping me quite a bit so far.

One issue I have found is that it seems to block the Copy function from the Snipping Tool builtin to Windows 10 (previous versions of Windows had it as well)

When you use the snipping tool it puts a section of a screen grab in your clipboard and this isn't happening when Shapeshifter is running. I am using the latest release version of 6 (6.1.19990.0) at the time of this post.

The Copy button in the Snipping Tool doesn't work either. If i exit Shapeshifter it works again.

Let me know if you need more information.

Keep up the good work!
![image](https://cloud.githubusercontent.com/assets/5911842/24806756/e51a1284-1b83-11e7-962c-6b209f2252ad.png)

**Comment by ffMathy** [comment]
Wow, this is quite critical. I'll get it fixed soon!

**Comment by nazuna1** [comment]
Add: Shapeshifter isn't work with images. 
For exam, Snipping Tool's copy button or Ctrl + C is not work where Shapeshifter worked.
Copying in Photoshop does not work.
Illustrator, Painter, Word, PPT.... etc.
Shapeshifter can not process image files.
It's very critical.

**Comment by TheGreatYamcha** [comment]
I also had the same problem with OneNote's screen capture.
It used to work fine in version 5.0

**Comment by V-Edu** [comment]
Experiencing the same issue... It doesn't process the images and I'm using version 5 for this reason.
OS: Windows 10
Keep the hard work! It's really a great tool!

**Comment by ffMathy** [comment]
Will fix soon.

**Comment by ffMathy** [comment]
In the latest version, the image now shows up in Shapeshifter but still can't be pasted. Still working on it!

**Comment by ffMathy** [comment]
Getting a lot closer!

**Comment by ffMathy** [comment]
Alright, latest deployed release now understands image formats also taken by Lightshot. Still needs to be able to paste.

**Comment by ffMathy** [comment]
Alright, I managed to make copying work for 32 bit color schemes. Still need the others to work too.

Currently getting inspiration from here, where they are doing something similar:
https://raw.githubusercontent.com/ddavison/greenshot/master/GreenshotPlugin/Core/ClipboardHelper.cs

**Comment by ffMathy** [comment]
More resources I am using:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd183391(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/dd183374(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/ff729168(v=vs.85).aspx

**Comment by KoalaBear84** [comment]
Couple of days ago I've TRIED to 'serialize' the complete clipboard. Was just testing to see if it was possible.

I can read all what's on the Clipboard, but restoring it in the EXACT the same way is failing. And I don't know why, learned some about clipboard formats, but restoring is hard.

Also wanted to try this because of RDP file transfers, but that looks like it is really impossible to because of file streams and pointers which 'disappear' or are not restorable after 'freed' because I've copied something else.

Here is my not working proof of concept. MAYBE there is some piece of code that might be helpful.

[ClipboardPoc.zip](https://github.com/ffMathy/Shapeshifter/files/1945562/ClipboardPoc.zip)

**Comment by ffMathy** [comment]
Holy shit Koala I freaking love you! Great job!

As for streams, I think it is because a stream is exposed live. A stream by definition is not actually data that fully exists yet, but allows the reader to request more data along the way.

I think if Shapeshifter internally stored a pointer to the stream inside of itself first, and then when setting the clipboard data again it would open its own stream and put that on the clipboard. Then, when someone reads from that stream, it live reads and proxies the original stream and forwards the data. 

Should be possible.

**Comment by KoalaBear84** [comment]
No problem, hope I can be of any help! Let's hope it is possible.

**Comment by ffMathy** [comment]
This has finally been resolved! Image pasting in all formats works, and even with DIBV5 format, meaning that all formats should be compatible, since it can auto-convert to all the other image formats!
