### ISSUE TITLE
strange traffic

### ISSUE THREAD

**Issue by Trueinsanity** [ffMathy/Shapeshifter#204]
for some reason i am showing traffic coming to and from survey-winner.com as seen in screen shot in link [http://imgur.com/a/0gdhI](url)

![](http://i.imgur.com/X7gDePM.png)

do you know what this might be?

**Comment by Rene-Sackers** [comment]
It's a guess, but Shapeshifter may download an image of a URL you copied, which may respond with a HTTP redirect status code (to survey-winner.com), possibly causing it to download data from that site.

@ffMathy I'm sure you can confirm this.

**Comment by Trueinsanity** [comment]
it is true that i have yet to see the traffic occur again, so could have been from something i copied

**Comment by ffMathy** [comment]
If this is the old Shapeshifter 5 which is no longer supported, it will be because it attempts to check for updates on flamefusion.net, a site we no longer have the funds to keep open, and aren't paying for anymore. 

If you go to that site now it will instead redirect to some ads or some parking site because we are not in control of it anymore. It contacts this site to check for updates every once in a while, but obviously can't find any since the site doesn't exist. 

If this is Shapeshifter 6, then @Rene-Sackers is right. When you copy some text for instance, Shapeshifter will perform a DNS query towards something if it believes a part of the text is a domain. If the DNS query succeeds, it will allow you to open the domain itself. 

However, other than that, Shapeshifter 6 shouldn't perform any web requests. It will check for updates directly here on GitHub. 

Which version are you using?

**Comment by Trueinsanity** [comment]
sorry about delay, but i checked and was using version 5. thanks for the assistance
