### ISSUE TITLE
Shapeshifter sometimes doesn't register copied files

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#26]
I still can't figure out in which scenarios this happens and why. If anybody else knows what's causing this, feel free to join in on the discussion.

**Comment by KoalaBear84** [comment]
I'm finally debugging in the right parts of the code :P

For me a job at it's own. It's setup perfectly decoupled, but if you didn't create it, it's complex.

I see it detects the right clipboard format 15, which is CF_HDROP, which is a list of files.
https://msdn.microsoft.com/en-us/library/windows/desktop/ff729168%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

It takes the GeneralUnwrapper. It unwraps rawData of 144 bytes in this case. HUH.. Now I did drag the breakpoint cursor back up, and run the exact same code, and it now DID a succesfull factory.BuildData(format, rawData), but nothing changed... Just the previous run it returned null from factory.BuildData.

I now dragged it multiple times to the first line of `DecoratePackageWithDataUsingFactory` and 4 out of 5 times it does not work. Which returns empty packages and therefore gives you 'invisible' items in the userinterface.

Sometimes it just does not return files from `GetFilesCopiedFromRawData`... Or the problem is something with the MemoryHandleFactory, or it is the ClipboardApi.DragQueryFile?

**Comment by ffMathy** [comment]
Thanks for the effort.

Yes, that is indeed the issue. Sometimes, it just returns count `0` when querying how many files there is on the specified handle.

It says in the documentation [here](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776408(v=vs.85).aspx) states:

> A nonzero value indicates a successful call.

It would be interesting to implement a retrying mechanism that retries something for X amount of times, and see if that helps. Maybe it's just how it's supposed to be?

Could you try working on that and see if it helps?

I appreciate all the learning effort you've spent on trying to understand the code. So cool!

**Comment by KoalaBear84** [comment]
Yes, will do. First I will try to see others experiencing it and see if there is something to fix. Else it will be some sort of workaround...

**Comment by ffMathy** [comment]
I think retrying is fine to be honest. Try a mechanism that retries 1000 times (yes, I know that's a lot), and then see if that *always* succeeds. If it does, we'll see at what point it becomes stable, and use that count.

**Comment by ffMathy** [comment]
Nice. a055eca8 seems to fix this issue.
