### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#271]
Shapeshifter's icon kind of sucks especially when it's in the tray.

**Comment by ffMathy** [comment]
I was thinking this could be the new icon: https://material.io/icons/#ic_content_copy

We just need a larger version, and then we need something that has a slight black border around it (like Slack or OneDrive has).

**Comment by thegabriestein** [comment]
Hmm, yeah it could do with some increased branding. Maybe something from here? Should probably be an overall consistent logo though. I think I have some credits here:
https://www.iconfinder.com/search/?q=copy&price=premium

**Comment by ffMathy** [comment]
I'm not only concerned with branding but also how it looks when scaled down in the tray.

Furthermore, we should probably give it a color.

**Comment by thegabrielstein** [comment]
Agreed. How about any of these icons and / or colors?
https://www.iconfinder.com/icons/3074622/clipboard_copy_essentials_icon#size=512
https://www.iconfinder.com/icons/2538417/copy_duplicate_paste_icon#size=512
https://www.iconfinder.com/icons/1472933/copy_popup_windows_icon#size=512
https://www.iconfinder.com/icons/3171171/copy_layers_objects_swap_icon#size=512
https://www.iconfinder.com/icons/397432/copy_data_document_duplicate_file_layer_share_icon#size=512

Also, maybe pick a color from here:
https://flatuicolors.com/

And then extrapolate for complimentary colors here?
https://www.sessions.edu/color-calculator/

**Comment by KoalaBear84** [comment]
I'm also not sure. Was experimenting with some, with the first one Mathias sent, and colored it. It hard to get a nice icon for 16 x 16. But it looks ok.

![image](https://user-images.githubusercontent.com/5886900/39661868-73733cd0-5059-11e8-8cef-5021cec5ee37.png)

**Comment by thegabrielstein** [comment]
Yeah I think an icon along those lines is a good choice, and a brighter color will probably serve better since most (all?) Windows taskbars 8 or 10+ will contrast better with a bright color?

And because it's raster, once you get to 16x16, anything rounded is suffering. So ideally something fairly squared up. Also, once you establish a mental anchor of the icon in someones head, you don't need to have a large scale version of it to trigger memory as long as it's unique and good (also a good tool tip will help people remember what it is).

If you set the background to dark, it's easy to look through these for ones that jump out right away:
https://www.iconfinder.com/search/?q=copy&maximum=16&price=premium

**Comment by ffMathy** [comment]
Hmmm that looks nice! I will go with that. Not sure about the color though. I'm wondering if we should go with white for the tray icon, and then have a colored one for the application icon itself. 

But what color to choose? I wonder if we should then have some gradient in it and perhaps even some border around it.

**Comment by ffMathy** [comment]
For the tray icon I would go with just white without borders. I'm thinking about the application icon used for the file when viewing it in explorer 😊

**Comment by thegabrielstein** [comment]
Gotcha. Yeah it needs to be universally consistent, but a white icon would cause problems on an explorer background unless modified.

**Comment by ffMathy** [comment]
Done!
