### ISSUE TITLE
Active screen is calculated wrong

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#280]
Sometimes it even leads to crashes. Furthermore, the orientation is off. Perhaps test with a virtual display.

**Comment by thegabriestein** [comment]
Seems to work fairly well with my setup even though it's 3 large monitors and some weird shapes. It works well on the horizontal monitors, but definitely freaks out on my vertical monitor. It has had some nasty crashes in the past though.

Ideally active window is probably the safest because that's where the actual paste content will end up anyway, so could actually help cue the user that they might paste into the wrong window if it doesn't show up near what they're working on.

**Comment by ffMathy** [comment]
This has now been potentially fixed, although not sure yet. Don't have a proper setup to test yet. Will re-open if it's not.
