### ISSUE TITLE
Update website with Patreon supporters slider

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#286]
In #227 I created a website for Shapeshifter.

This website should also display Patreon supporters and a link to become a supporter.

**Comment by szepeviktor** [comment]
You can have 1 website issue with a todo list in it

- [ ] number 1
- [ ] number 2
- [ ] number 3

**Comment by ffMathy** [comment]
What do you mean with website issue? 🙂

**Comment by KoalaBear84** [comment]
He means this, create one github issue, and use task lists:
https://help.github.com/articles/about-task-lists/

**Comment by ffMathy** [comment]
But for what? Oh, instead of making this many issues or?

**Comment by thegabriestein** [comment]
@ffMathy I believe that @szepeviktor is talking about having a checklist of items under this issue #286 for creating the website. 

So instead of "Should also display patreon supporters, and a link to become a support", it could look like this:

Add to website:
- [ ] Display Patreon supporters
- [ ] Become a Supporter link
- [x] Screenshot

Didn't realize that was there haha, really cool formatting feature for issues where there's a couple sub tasks.

**Comment by ffMathy** [comment]
Fixed.
