### ISSUE TITLE
Greenshot compatibility

### ISSUE THREAD

**Issue by KoalaBear84** [ffMathy/Shapeshifter#290]
Snipping Tool is fixed with #200, but unfortunately it is not fix for Greenshot, or a lot of other tools probably.

With the ClipboardPoc tool in #200 and with [InsideClipboard](https://www.nirsoft.net/utils/inside_clipboard.html) it gives me the following:
**Snipping Tool**

_Poc:_
Index: [0], System.Drawing.Bitmap [49764], System.Drawing.Bitmap
Index: [1], Bitmap [2], System.Drawing.Bitmap
Index: [2], DeviceIndependentBitmap [8], System.IO.MemoryStream
Index: [3], Format17 [17], System.IO.MemoryStream

_InsideClipboard:_
2	CF_BITMAP	Bitmap	0	1	
8	CF_DIB	Memory	90,692	2	
17	CF_DIBV5	Memory	90,776	3	

**Greenshot**

_Poc:_
Index: [0], PNG [49284], System.IO.MemoryStream
Index: [1], DeviceIndependentBitmap [8], System.IO.MemoryStream

_InsideClipboard:_
49284	PNG	Memory	1,279	1	
8	CF_DIB	Memory	114,088	2	

I don't know the exact inner workings, but I guess it is now a little too specific on the System.Drawing.Bitmap part, and now supporting these MemoryStreams.

Or, I saw that it looked at DIBV5 specifically, which in not present in Greenshot. Also it would be good to support PNG as it might fit better for certain destination programs, also in this example it is 100 times smaller.

The best thing would be to fully save the clipboard data in all formats, and restore in all formats. I didn't succeed in the with the DataObject class, but maybe you have more understanding how it works, or how to deliver the right format's to it.

**Comment by ffMathy** [comment]
DIBV5 should auto-convert to DIB. There must be something else wrong, but it should be easy to fix now!

I'll leave this issue open for now. I won't have time to work on Shapeshifter until Tuesday next week, but then I will focus on this!

@thegabriestein given that we've fixed so many bugs, wouldn't you say we can do our buddy @KoalaBear84  by prioritizing this to the top of the "stability" board?

**Comment by KoalaBear84** [comment]
Hmm, didn't know Nirsoft also had some clipboard manager. The only thing I miss is the beautiful GUI with CTRL + V support. :P

This one does 'serialize' it and can also 'serialize' it exactly as it was, but also does not work with RDP :P
http://www.nirsoft.net/utils/clipboardic.html

**Comment by thegabriestein** [comment]
@ffMathy Man, check out that link, this is why Shapeshifter needs to exist haha. Not even a competition!

**Comment by KoalaBear84** [comment]
Maybe you can use some bits from Greenshot itself which places the picture on the Clipboard.

https://github.com/greenshot/greenshot/blob/a733522b1d9c1c87222b5384f482a35c9b19ab01/src/Greenshot.Addons/Core/ClipboardHelper.cs

**Comment by ffMathy** [comment]
Alright, almost there. Since #275 is now resolved, this is almost ready too.

The remaining issue is auto-translation which I am working on. Greenshot stores its screenshots as `CF_DIB`, which (if `CF_DIBV5` is requested) will auto-convert. The only problem is that Shapeshifter doesn't understand which formats will auto-convert, and explicitly asks for `CF_DIBV5`.

See: https://msdn.microsoft.com/en-us/library/windows/desktop/ms649013(v=vs.85).aspx#_win32_Synthesized_Clipboard_Formats

**Comment by KoalaBear84** [comment]
I see Windows should already have fixed this incompatibility indeed. Strange.

**Comment by ffMathy** [comment]
Well it is working. It's just a simple bug causing Shapeshifter to not actually request the data correctly.

I'll try to elaborate what happens today.

1. Greenshot stores the image as `CF_DIB`. This format should be able to auto-convert to `CF_DIBV5` as per the API.
2. Shapeshifter enumerates all clipboard formats. This **only** returns `CF_DIB`.
3. It then asks the unwrappers if they can handle that format. The `CF_DIBV5` wrapper says "nope, can't do that".

So the problem is simply that Shapeshifter needs to _ask_ for `CF_DIBV5` even when only `CF_DIB` is present. It's currently only asking for things that are present.

I have it working on my local machine! Only minor concern I'm working on right now is minor bugs.

**Comment by KoalaBear84** [comment]
Yes I understand, thanks for your explanation. It looks like indeed Windows is only providing the auto-convert IF it is requested indeed. Maybe it is needed for more auto-convert formats, strange that it is needed.

**Comment by ffMathy** [comment]
Greenshot confirmed working - coming up in new prerelease soon!

**Comment by ffMathy** [comment]
Done!
