### ISSUE TITLE
Excel Clipboard

### ISSUE THREAD

**Issue by jkdalton** [ffMathy/Shapeshifter#3]
I've always had issues with this program working with Excel. In my opinion, that is the primary thing holding this software back. Ctrl Alt V to paste special does not agree with excel especially. I also see the same issue when pressing Ctrl Alt V, then lifting Ctrl up before V to negate the paste. This is when the Ctrl button Sticks (until Ctrl is toggled on and off manually again).

**Comment by ffMathy** [comment]
Thanks for this suggestion. We'll see if we can get that fixed in the future release. The problem with the Windows clipboard is that it is inconcistent. Programs can store data in it in any way that they choose. This means that it can be hard for us to be compatible with all versions of Office, while still not compromising the experience.

I'm sure we'll find a way though. I'll mark this as complete when we get it implemented.

**Comment by ffMathy** [comment]
Note to self: It could be possible to create stabilizers injected via IOC to "stabilize" input that is denormalized.

**Comment by ffMathy** [comment]
@jkdalton can you see if this is still a problem with the latest Shapeshifter 6 beta?
