### ISSUE TITLE
Save clipboard history to disk

### ISSUE THREAD

**Issue by KoalaBear84** [ffMathy/Shapeshifter#31]
Always had some thoughts about this. You reboot your computer and you will not lose your clipboard history :D

Yes, this is a feature request for a far future is everything else is OK!

**Comment by ffMathy** [comment]
This will be implemented in the beta version as well. We already serialize all data as byte. See `IClipboardData`. It has a `RawData` byte array.

**Comment by ffMathy** [comment]
I have now implemented so called "unwrappers" which support taking clipboard data and turning it into a uniform byte format. This will be able to be persisted. Still need to implement the rest though.

**Comment by ffMathy** [comment]
The latest commit I just made (bbfa6bc) improves this issue, but still persists items in temporary storage, and doesn't retrieve them again.

Shapeshifter can now "Pin" items since it has a "Pin" action.

We still need to persist them permanently though, and also we need to work on re-fetching them. Functionality is already there in a `ClipboardPersistanceService`. Maybe you can do the rest if you get the time?

We also need an "UnpinAction" (right now there is only an action for pinning non-pinned items, we need to also be able to unpin pinned ones).

**Comment by ffMathy** [comment]
e2f0ace adds tests for this, but it is still not called on startup. Still need to work on that part.

**Comment by ffMathy** [comment]
This has now been finalized.
