### ISSUE TITLE
Increase exposure to website

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#403]
The `readme.md` file should (instead of pointing to download links and Patreon) point to the website instead I think.

We need to make more people aware of the website.

What do you think @thegabrielstein? And is this something you could perhaps work on? :+1:

**Comment by ffMathy** [comment]
Done.

**Comment by KoalaBear84** [comment]
Yesterday I updated the icon on AlternativeTo, today it was approved. I needed to wait for the approval to be able to update it again because I'm not the owner.

https://alternativeto.net/software/shapeshifter/

When Shapeshifter is stable enough for more users I will put some more energy in this part and will also add it to the biggest Dutch technology site.

**Comment by ffMathy** [comment]
So freaking awesome! Thanks!!!

**Comment by thegabrielstein** [comment]
Awesome! Yeah any sites like that are great. Maybe G2 Crowd and Capterra etc? Also once it's rock solid, trying to get it featured in Zapier or IFTTT blog etc would be killer. Sucks that we were a little late to this post:
https://zapier.com/blog/best-clipboard-managers/

Maybe we can get it posthumously added haha?
