### ISSUE TITLE
Notification counter resets after some time

### ISSUE THREAD

**Issue by svenjochems** [ffMathy/Shapeshifter#525]
I've notices that after some time the notification counter restarts back at 1 after some time while more items are still in the list.

**To Reproduce**
1. Copy item: notification counter 1
2. Copy item: notification counter 2
3. Wait a few minutes...
4. Copy item: notification counter 1

**Expected behavior**
I would expect notification counter 3 because there are 3 items in the list

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 6.2018.518.2771

**Additional context**
I'm not sure yet if a specific action causes this or how long the wait is to trigger this.

**Comment by svenjochems** [comment]
Correction: It seems like each copy source has his own counter, so its more like this:

1. Copy item from notepad: notification counter 1
2. Copy item from notepad: notification counter 2
3. Copy item from browser: notification counter 1

I'm not sure if this is expected behavior. If so, this issue can be closed.

**Comment by ffMathy** [comment]
The counter is based on windows, not processes. So if you change between windows within the same process, the counter will reset.

Do you want the counter to be global instead? I think a counter per application makes more sense.

Perhaps we could also show the counts for all applications on the fly, so that it will show more application icons and their counts next to it.

**Comment by svenjochems** [comment]
It caused some confusion at first but maybe it does make more sense indeed.
I am personally in favor for as less notifications as possible, but this feature is already addressed at #400

**Comment by ffMathy** [comment]
Great, and thanks for your feedback!
