### ISSUE TITLE
Switch away from regular expressions for domain scanning

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#541]
We could boost performance radically by determining if something is a link as follows.

1. It has one or more dots in it, but doesn't end or start with a dot.
2. It it has slashes in it.
3. It has & or ? in it.

From those, we could extract the domain name also without regular expressions.

**Comment by KoalaBear84** [comment]
Regular expressions are not always bad performance wise. The current (or now previous one) found way too much I think. Like "shapeshifter.exe" which it also see as a domain.

We could also make it so that it needs to contain http(s), and, or contains www. It might not be 100% accurate, but there it no real 100% method otherwise than sometimes scanning thousands of 'domains'.

I think the main reason the current mechanism does not work OK is because i THINK it also parsed plain RTF data as 'text'. It should only scan the real output of the RTF text, not the RTF data format itself. At least that is what I thought it did. It scanned everything, and you won't find any domains inside this:
```{\rtf\ansi\deff0{\fonttbl{\f0\froman Tms Rmn;}{\f1\fdecor 
Symbol;}{\f2\fswiss Helv;}}{\colortbl;\red0\green0\blue0;
\red0\green0\blue255;\red0\green255\blue255;\red0\green255\
blue0;\red255\green0\blue255;\red255\green0\blue0;\red255\
green255\blue0;\red255\green255\blue255;}{\stylesheet{\fs20 \snext0Normal;}}{\info{\author John Doe}
{\creatim\yr1990\mo7\dy30\hr10\min48}{\version1}{\edmins0}
{\nofpages1}{\nofwords0}{\nofchars0}{\vern8351}}\widoctrl\ftnbj \sectd\linex0\endnhere \pard\plain \fs20 This is plain text.\par}```

**Comment by ffMathy** [comment]
This has been fixed - it is now very fast.
